### ISSUE TITLE
Customization script fails on AlmaLinux 8.3 beta

### ISSUE THREAD

**Issue by corporate-gadfly** [vmware/open-vm-tools#497]
I have a source VM with Alma Linux 8.3 beta template. When creating a new VM, using this template, customization script fails. 

I have looked at http://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf, and I don't see AlmaLinux as supported currently.

Is there anything I can provide to help get AlmaLinux supported?
```
# vmtoolsd --version
VMware Tools daemon, version 11.1.0.19887 (build-16036546)
```
```
# rpm -qa | grep open-vm-tools
open-vm-tools-11.1.0-2.el8.x86_64
```
```
# cat /etc/system-release
AlmaLinux release 8.3 Beta (Purple Manul)
```
[/var/log/vmware-imc/toolsDeployPkg.log](https://github.com/vmware/open-vm-tools/files/6018745/toolsDeployPkg.log)

**Comment by PengpengSun** [comment]
Hi,

The error you see in the toolsDeployPkg.log is not a customization failure, I can see the customization script executed completely in your VM.  As you know, AlmaLinux is not supported, so no guarantee that customization script can work well on AlmaLinux.

Back to the error, the reason is customization executes /sbin/telinit command repeatedly to reboot VM,  the repeated command could raise error since rebooting has been in progress. This is a known issue and has been fixed in future vmtools version.

**Comment by corporate-gadfly** [comment]
Thank you for the response.

Is it worth keeping this issue open until a new version of vmtools is released?

**Comment by PengpengSun** [comment]
I'm not sure what's the strategy of AlmaLinux, it usually takes some time for a Linux vendor to adapt the latest open-vm-tools release,  and since the error is not a customization failure, this issue can be closed now.

**Comment by corporate-gadfly** [comment]
Same issue with AlmaLinux 8.3 RC. Closing.

**Comment by jaboutboul** [comment]
@corporate-gadfly we are actively working with VMWare to have AlmaLinux supported as a guest OS and across the full array of VMWare's product suite as well.

**Comment by corporate-gadfly** [comment]
@jaboutboul : any updates?

**Comment by thatsk** [comment]
any updates?

**Comment by thatsk** [comment]
facing issue on alma 8.7
and 9.1 too

**Comment by PengpengSun** [comment]
Please check http://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf,  AlmaLinux OS 8.x support starts from vSphere 6.x (See [KB 85686](https://kb.vmware.com/s/article/85686)), AlmaLinux OS 9.x support starts from vSphere 7.x (See [KB 85686](https://kb.vmware.com/s/article/85686) and [KB 88199](https://kb.vmware.com/s/article/88199))
And please share /var/log/vmware-imc/toolsDeployPkg.log from VM you are seeing issues here. @thatsk @corporate-gadfly

**Comment by thatsk** [comment]
@pengrongbo Thanks for the reply I tried this way also I am attaching logs.
before updating /etc/redhat-release. **toolsDeploypkg.log**
after updating /etc/redhat-release to CentOS Linux **toolsDeployPkg1.log**

If I manually update it via the centre it just connects.

open-vm-tools-12.1.5-1.el8.x86_64

Cloud-Init configuration:-
```
cat << EOF > /etc/cloud/cloud.cfg.d/01_network.cfg
network:
  config: disabled
EOF

cat << EOF > /etc/cloud/cloud.cfg
# Default redhat settings:
ssh_deletekeys:   true
ssh_genkeytypes:  ['rsa', 'ecdsa', 'ed25519']
syslog_fix_perms: ~
disable_vmware_customization: false
cloud_init_modules:
 - bootcmd
cloud_config_modules:
 - runcmd
cloud_final_modules:
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - phone-home
system_info:
  distro: almalinux
  paths:
    cloud_dir: /var/lib/cloud
    templates_dir: /etc/cloud/templates
  ssh_svcname: sshd
EOF
```
