### ISSUE TITLE
Oracle Linux 7 (64bit) support

### ISSUE THREAD

**Issue by neuhaus** [vmware/open-vm-tools#563]
### Describe the bug

I'm trying to create a VM with ansible and community.vmware `vmware_guest` using a template i created from a freshly installed Oracle Linux 7.9 64bit VM (i merely ran `yum update` and `yum install perl`).

Here's the error message i am seeing:

`Failed to create a virtual machine : Customization of the guest operating system 'oracleLinux7_64Guest' is not supported in this configuration.`

### Reproduction steps

```bash
try to configure a Oracle Linux 7 64bit VM
```

### Expected behavior

it should configure the VM without an error message

### Additional context

Parameters given:
```
  vmware_guest:
    hostname: ...
    username: ...
    password: ...
    validate_certs: ...
    name: ...
    datacenter: ...
    folder: ...
    template: ...
    datastore: ...
    hardware: ...
    disk: ...
    networks: ...
    customization:
      dns_servers: ...
      hostname: ...
      timezone: "Europe/Berlin"
    wait_for_customization: yes
    wait_for_ip_address: True
    state: poweredon
```

**Comment by PengpengSun** [comment]
Hi @neuhaus ,

Have you installed open-vm-tools? If not, please run `yum install open-vm-tools` to install it on your template firstly, If yes, please share its version by running `vmtoolsd -v`.

Best regards,
Pengpeng

**Comment by Tomorrow9** [comment]
I had a try on below playbook to deploy a new VM using OL7.9 template on vSphere 7.0.2, open-vm-tools installed in guest OS is 11.0.5. New VM can be created and customized without error.
```
- hosts: localhost
  tasks:
    - name: test customize
      vmware_guest:
        hostname: xx.xx.xx.xx
        username: xxxx
        password: xxxx
        validate_certs: False
        name: dw_test_ol79
        datacenter: 70U2
        folder: ""
        template: "dw-OL7.9_64bit_OVT"
        datastore: ds1
        networks:
          - name: "VM Network"
            type: dhcp
        customization:
          dns_servers: "192.168.0.1"
          hostname: dw_test
          timezone: "Europe/Berlin"
        wait_for_customization: yes
        wait_for_ip_address: True
        state: poweredon
```
